sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t client-ci -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true client-ci npm run test

after_success:
  - docker build -t tchappel/fibonacci-client ./client
  - docker build -t tchappel/fibonacci-nginx ./nginx
  - docker build -t tchappel/fibonacci-server ./server
  - docker build -t tchappel/fibonacci-worker ./worker
  # Login to the DockerCLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to DockerHub
  - docker push tchappel/fibonacci-client
  - docker push tchappel/fibonacci-nginx
  - docker push tchappel/fibonacci-server
  - docker push tchappel/fibonacci-worker
